"""FastPassword REST API — modeled on the 1Password Connect API.

Mounted at ``/api``; the versioned REST surface lives under ``/api/v1``. Interactive
docs are generated by FastAPI:

* Swagger UI   → ``/api/docs``
* ReDoc        → ``/api/redoc``
* OpenAPI JSON → ``/api/openapi.json``

Authentication is a **Bearer token** (a personal access token minted in the app at
Settings → API tokens, shown once, prefixed ``fpw_``):

    Authorization: Bearer fpw_xxxxxxxx…

Token scopes:
  * ``read``  — list vaults and items, and read an item **including its secret
    field values** (getting a single item reveals its concealed fields, exactly
    like 1Password Connect).
  * ``write`` — create and delete items.

A token can only reach the vaults its owner is a member of.
"""
from __future__ import annotations

from fastapi import Depends, FastAPI, HTTPException, Path, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field

from . import db
from .version import VERSION

DESCRIPTION = (
    "Programmatic access to your FastPassword vaults, modeled on the 1Password "
    "Connect API. Authenticate with a Bearer token (Settings → API tokens). "
    "Reading a single item returns its secret field values; tokens are scoped to "
    "the vaults their owner belongs to."
)

api = FastAPI(
    title="FastPassword API",
    version=VERSION,
    description=DESCRIPTION,
    openapi_tags=[
        {"name": "Vaults", "description": "List the vaults the token can access."},
        {"name": "Items", "description": "List, read, create and delete items. "
                                         "Reading an item returns its secret fields."},
        {"name": "Health", "description": "Service and password-health checks."},
    ],
)

_bearer = HTTPBearer(auto_error=False, description="Personal access token, prefixed `fpw_`.")

_CATEGORY = {"login": "LOGIN", "credential": "API_CREDENTIAL"}
_CATEGORY_IN = {v: k for k, v in _CATEGORY.items()}


# ── auth dependencies ────────────────────────────────────────────────────────
def _context(creds: HTTPAuthorizationCredentials | None = Depends(_bearer)):
    if not creds or creds.scheme.lower() != "bearer":
        raise HTTPException(status_code=401, detail="Missing Bearer token",
                            headers={"WWW-Authenticate": "Bearer"})
    ctx = db.resolve_api_token(creds.credentials)
    if not ctx:
        raise HTTPException(status_code=401, detail="Invalid, expired, or revoked token",
                            headers={"WWW-Authenticate": "Bearer"})
    return ctx


def _need(scope: str):
    def dep(ctx=Depends(_context)):
        if scope not in ctx["scopes"]:
            raise HTTPException(status_code=403, detail=f"Token is missing the '{scope}' scope")
        return ctx
    return dep


# ── serializers (1Password-style shapes) ─────────────────────────────────────
def _vault_json(v):
    return {"id": str(v["id"]), "name": v["name"], "description": v.get("description") or "",
            "type": "PERSONAL" if v["kind"] == "personal" else "USER_CREATED",
            "items": v.get("item_count", 0), "attributeVersion": v.get("member_count", 0),
            "createdAt": v.get("created_at"), "updatedAt": v.get("updated_at")}


def _urls(it):
    return [{"href": it["url"], "primary": True}] if it["url"] else []


def _item_summary(it, vault_id=None):
    return {"id": str(it["id"]), "title": it["title"],
            "vault": {"id": str(vault_id or it["vault_id"])},
            "category": _CATEGORY.get(it["type"], "LOGIN"),
            "urls": _urls(it), "favorite": bool(it["favorite"]), "tags": [],
            "version": it["version"], "createdAt": it["created_at"], "updatedAt": it["updated_at"]}


def _item_full(it, fields):
    out = _item_summary(it)
    f = []
    if it["username"]:
        f.append({"id": "username", "type": "STRING", "purpose": "USERNAME",
                  "label": "username", "value": it["username"]})
    secret = fields.get("password") or fields.get("secret")
    if secret:
        f.append({"id": "password", "type": "CONCEALED", "purpose": "PASSWORD",
                  "label": "password" if it["type"] == "login" else "credential", "value": secret})
    if fields.get("notes"):
        f.append({"id": "notesPlain", "type": "STRING", "purpose": "NOTES",
                  "label": "notesPlain", "value": fields["notes"]})
    for label, value in (fields.get("custom") or {}).items():
        f.append({"id": f"custom_{label}", "type": "STRING", "purpose": "",
                  "label": label, "value": value})
    out["fields"] = f
    return out


# ── request models ───────────────────────────────────────────────────────────
class FieldIn(BaseModel):
    label: str | None = None
    value: str = ""
    purpose: str | None = Field(default=None, description="USERNAME | PASSWORD | NOTES")
    type: str | None = None


class ItemIn(BaseModel):
    title: str
    category: str = Field(default="LOGIN", description="LOGIN | API_CREDENTIAL")
    urls: list[dict] = []
    fields: list[FieldIn] = []

    model_config = {"json_schema_extra": {"example": {
        "title": "GitHub", "category": "LOGIN",
        "urls": [{"href": "https://github.com", "primary": True}],
        "fields": [{"purpose": "USERNAME", "value": "octocat"},
                   {"purpose": "PASSWORD", "value": "correct-horse-battery"},
                   {"label": "recovery", "value": "codes here"}]}}}


def _parse_item(body: ItemIn):
    item_type = _CATEGORY_IN.get(body.category.upper(), "login")
    url = ""
    for u in body.urls:
        if u.get("href"):
            url = u["href"]
            if u.get("primary"):
                break
    username, secret, notes, custom = "", "", "", {}
    for fld in body.fields:
        purpose = (fld.purpose or "").upper()
        if purpose == "USERNAME":
            username = fld.value
        elif purpose == "PASSWORD":
            secret = fld.value
        elif purpose == "NOTES":
            notes = fld.value
        elif fld.label:
            custom[fld.label] = fld.value
    fields = {}
    if secret:
        fields["password" if item_type == "login" else "secret"] = secret
    if notes:
        fields["notes"] = notes
    if custom:
        fields["custom"] = custom
    return item_type, url, username, fields


# ── vaults ───────────────────────────────────────────────────────────────────
@api.get("/v1/vaults", tags=["Vaults"], summary="List vaults")
def list_vaults(ctx=Depends(_need("read"))):
    return [_vault_json(v) for v in db.vaults_for(ctx["identity"])]


@api.get("/v1/vaults/{vault_id}", tags=["Vaults"], summary="Get a vault")
def get_vault(vault_id: int, ctx=Depends(_need("read"))):
    if not db.can_view_vault(ctx["identity"], vault_id):
        raise HTTPException(status_code=404, detail="Vault not found")
    v = next((x for x in db.vaults_for(ctx["identity"]) if x["id"] == vault_id), None)
    return _vault_json(v)


# ── items ────────────────────────────────────────────────────────────────────
@api.get("/v1/vaults/{vault_id}/items", tags=["Items"], summary="List items in a vault")
def list_items(vault_id: int, ctx=Depends(_need("read"))):
    if not db.can_view_vault(ctx["identity"], vault_id):
        raise HTTPException(status_code=404, detail="Vault not found")
    return [_item_summary(i, vault_id) for i in db.items_in_vault(vault_id)]


@api.get("/v1/vaults/{vault_id}/items/{item_id}", tags=["Items"],
         summary="Get an item (returns its secret fields)")
def get_item(vault_id: int, item_id: int, ctx=Depends(_need("read"))):
    it = db.viewable_item(ctx["identity"], item_id)
    if not it or it["vault_id"] != vault_id:
        raise HTTPException(status_code=404, detail="Item not found")
    fields = db.reveal(ctx["identity"], item_id) or {}
    return _item_full(it, fields)


@api.post("/v1/vaults/{vault_id}/items", tags=["Items"], status_code=201,
          summary="Create an item")
def create_item(vault_id: int, body: ItemIn, ctx=Depends(_need("write"))):
    if not db.can_edit_vault(ctx["identity"], vault_id):
        raise HTTPException(status_code=403, detail="Token cannot write to this vault")
    item_type, url, username, fields = _parse_item(body)
    iid = db.create_item(ctx["identity"], vault_id, type=item_type, title=body.title,
                         url=url, username=username, fields=fields)
    if iid is None:
        raise HTTPException(status_code=403, detail="Not permitted")
    return _item_full(db.item(iid), fields)


@api.delete("/v1/vaults/{vault_id}/items/{item_id}", tags=["Items"], status_code=204,
            summary="Delete an item")
def delete_item(vault_id: int, item_id: int, ctx=Depends(_need("write"))):
    it = db.item(item_id)
    if not it or it["vault_id"] != vault_id or not db.trash_item(ctx["identity"], item_id):
        raise HTTPException(status_code=404, detail="Item not found")
    return None


# ── health ───────────────────────────────────────────────────────────────────
@api.get("/v1/health-report", tags=["Health"], summary="Password health summary")
def health_report(ctx=Depends(_need("read"))):
    r = db.health_report(ctx["identity"])
    return {"score": r["score"], "total": r["total"], "weak": len(r["weak"]),
            "reused": len(r["reused"]), "old": len(r["old"])}


@api.get("/v1/me", tags=["Health"], summary="Identify the token owner")
def me(ctx=Depends(_context)):
    return {"email": ctx["identity"]["email"], "name": ctx["identity"]["name"],
            "scopes": ctx["scopes"]}


@api.get("/heartbeat", include_in_schema=False)
def heartbeat():
    return {"status": "ok", "product": "FastPassword", "version": VERSION}
